---
title: 'Advent Of Code: 2023-10'
author: Tan Ho
date: "2023-12-10"
output: 
  github_document:
    preserve_yaml: true
editor_options: 
  chunk_output_type: console
---

<https://adventofcode.com/2023/day/10>

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 10, year = 2023)
```

```{r}
m <- readLines(here::here("2023/day-10-input.txt")) |> 
  strsplit("") |> 
  do.call(what = rbind)

ind <- tidyr::crossing(
  row = seq_len(nrow(m)),
  col = seq_len(ncol(m))
) |> 
  dplyr::mutate(val = m[cbind(row,col)])

```

--- Part 1 ---

Setting up a breadth-first search. Joy.

```{r eval = FALSE}
next_steps <- function(x){
  opts <- switch(
    x$val,
    "S" = crossing(row = c(1,0,-1),col = c(1,0,-1)) |> dplyr::filter((abs(row) + abs(col))==1),
    "." = data.frame(row = numeric(), col = numeric()), 
    "-" = data.frame(row = c( 0, 0),  col = c( -1, 1)),
    "|" = data.frame(row = c( 1,-1),  col = c( 0, 0)),
    "F" = data.frame(row = c( 1, 0),  col = c( 0, 1)),
    "7" = data.frame(row = c( 1, 0),  col = c( 0, -1)),
    "J" = data.frame(row = c( -1, 0), col = c( 0, -1)),
    "L" = data.frame(row = c( -1, 0), col = c( 0, 1)),
  )
  
  candidates <- opts |> 
    dplyr::mutate(row = row + x$row, col = col + x$col)
  
  return(candidates)
}

start <- ind |> 
  dplyr::filter(val == "S") |> 
  dplyr::mutate(step = 0)

start_neighbours <- next_steps(start) |> 
  dplyr::inner_join(ind, by = c("row","col"))

queue <- start_neighbours |> 
  dplyr::filter(
    purrr::pmap_lgl(
      start_neighbours, 
      \(...) next_steps(list(...)) |> 
        dplyr::inner_join(start, by = c("row","col")) |> 
        nrow())
  ) |> 
  dplyr::mutate(step = 1)

completed <- start |> 
  # hardcode S value for start as '-'
  dplyr::mutate(val = "-") |> 
  dplyr::bind_rows(queue)

while(nrow(queue) > 0){
  x <- queue |> dplyr::slice(1)
  queue <- queue |> dplyr::slice(-1)
  
  q <- next_steps(x) |>
    dplyr::anti_join(completed, by = c("row","col")) |> 
    dplyr::anti_join(queue, by = c("row","col")) |> 
    dplyr::inner_join(ind, by = c("row","col"))
  
  if(nrow(q) > 0) {
    q <- q |> dplyr::mutate(step = x$step + 1)
    
    queue <- queue |> 
      dplyr::bind_rows(q)
  }
  
  completed <- completed |> 
    dplyr::bind_rows(q)
  
  if(nrow(completed) %% 1000 == 0) print(paste(nrow(completed), Sys.time()))
}
saveRDS(completed, "2023/day-10-checkpoint-1.rds")
max(completed$step)
```
```{r echo = FALSE}
6823
```

--- Part 2 ---

Triple the resolution of the grid, then for each value of the pipe ensure that
the corresponding are set correctly, then flood-fill it. Then find grid coordinates
where all nine points are inside the corresponding triple-resolution grid.

```{r eval = FALSE}
expand_pipes <- function(x){
  opts <- switch(
    x$val,
    "-" = data.frame(row = c( 0, 0),  col = c( -1, 1), val = c("-","-")),
    "|" = data.frame(row = c( 1,-1),  col = c( 0, 0), val = c("|","|")),
    "F" = data.frame(row = c( 1, 0),  col = c( 0, 1), val = c("|", "-")),
    "7" = data.frame(row = c( 1, 0),  col = c( 0, -1), val = c("|", "-")),
    "J" = data.frame(row = c( -1, 0), col = c( 0, -1), val = c("|", "-")),
    "L" = data.frame(row = c( -1, 0), col = c( 0, 1), val = c("|", "-"))
  )
  
  candidates <- opts |> 
    dplyr::mutate(row = row + x$row, col = col + x$col)
  
  return(candidates)
}

tripled_pipes <- dplyr::bind_rows(
  completed |> dplyr::transmute(row = row * 3, col = col * 3, val = val),
  purrr::pmap_dfr(
    completed |> dplyr::transmute(row = row * 3, col = col * 3, val = val),
    \(...) expand_pipes(list(...)))
) |> 
  dplyr::arrange(row,col)

search_grid <- tidyr::crossing(
  row = seq(min(tripled_pipes$row)- 1, max(tripled_pipes$row) + 1),
  col = seq(min(tripled_pipes$col)- 1, max(tripled_pipes$col) + 1)
)

srr <- c(min(tripled_pipes$row)- 1, max(tripled_pipes$row) + 1)
scr <- c(min(tripled_pipes$col)- 1, max(tripled_pipes$col) + 1)

search_points <- function(x){
  tibble::tibble(row = c(-1, 0, 0, 1) + x$row, col = c(0, -1, 1, 0)+x$col)
}

queue <- search_grid |> 
  dplyr::slice(1)

completed <- queue

while(nrow(queue) > 0){
  x <- queue |> dplyr::slice(1)
  queue <- queue |> dplyr::slice(-1)
  q <- search_points(x) |> 
    dplyr::filter(
      row >= srr[1], row <= srr[2],
      col >= scr[1], col <= scr[2]
    ) |> 
    dplyr::anti_join(tripled_pipes, by = c("row","col")) |> 
    dplyr::anti_join(completed, by = c("row","col"))
  if(nrow(q) > 0) {
    queue <- queue |> dplyr::bind_rows(q)
    completed <- completed |> dplyr::bind_rows(q)
  }
  if(nrow(completed) %% 5000 == 0) print(paste(Sys.time(),nrow(completed)))
}

io_grid <- dplyr::bind_rows(
  completed,
  full_pipes |> dplyr::select(row,col)
) |> 
  dplyr::mutate(inside = FALSE) |> 
  dplyr::left_join(x = search_grid, by = c("row","col")) |> 
  dplyr::mutate(inside = ifelse(is.na(inside), TRUE, inside))

orig_points <- readRDS("2023/day-10-checkpoint-1.rds") |> 
  dplyr::select(row,col) |> 
  tidyr::complete(row = seq(range(row)[1],range(row)[2]), col = seq(range(col)[1],range(col)[2])) |> 
  dplyr::mutate(row = row * 3, col = col * 3)

is_inside <- function(r,c){
  io_grid |> 
    dplyr::filter(
      row >= (r - 1), row <= (r + 1),
      col >= (c - 1), col <= (c + 1)
    ) |> 
    dplyr::summarise(all(inside)) |> 
    getElement(1)
}

purrr::map2_lgl(orig_points$row, orig_points$col, is_inside,.progress = TRUE) |> sum()
```
```{r echo=FALSE}
415
```


