---
title: 'Advent Of Code: 2023-02'
author: Tan Ho
date: "`r Sys.Date()`"
output: github_document
editor_options: 
  chunk_output_type: console
---

<https://adventofcode.com/2023/day/2>

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 2, year = 2023)
```

```{r}
input_raw <- readLines(here::here("2023/day-02-input.txt"))
input <- aoc.elf::aoc_read(day = 2, year = 2023)

x <- input |> 
  tidyr::separate(x, into = c("game", "values"), sep = ": ") |> 
  tidyr::separate_rows(values, sep = "; ") |> 
  dplyr::mutate(round = dplyr::row_number()) |> 
  tidyr::separate_rows(values, sep = ", ") |> 
  tidyr::separate(values, into = c("n", "color"), sep = " ", convert = T) |> 
  dplyr::select(game, round, color, n)
head(x)
```

--- Part 1 ---

```{r}
x |>
  dplyr::mutate(
    r1_ok = dplyr::case_when(
      color == "red" ~ n <= 12,
      color == "green" ~ n <= 13,
      color == "blue" ~ n <= 14
    )
  ) |> 
  dplyr::summarise(ok = all(r1_ok), .by = game) |> 
  dplyr::filter(ok) |> 
  getElement("game") |> 
  readr::parse_number() |> 
  sum()
```

--- Part 2 ---

```{r}
x |> 
  dplyr::group_by(game, color) |> 
  dplyr::summarise(req_n = max(n)) |> 
  dplyr::summarise(prod = prod(req_n)) |> 
  getElement("prod") |> 
  sum()
```

Much better today than yesterday. Happy with this. 
