---
title: 'Advent Of Code: 2023-19'
author: Tan Ho
date: "2023-12-19"
output: 
  github_document:
    preserve_yaml: true
editor_options: 
  chunk_output_type: console
---

<https://adventofcode.com/2023/day/19>

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 19, year = 2023)
```

```{r}
example_raw <- readLines(here::here("2023/day-19-example.txt"))
input_raw <- readLines(here::here("2023/day-19-input.txt"))

input <- input_raw

workflows <- input[seq(1, which(input == "")-1)] |> 
  tibble(x = _) |> 
  extract(x,into = c("workflow","rules"),"([a-z]+){(.+)}") |> 
  deframe()
  
ratings <- input[seq(which(input == "")+1,length(input))] |> 
  tibble(x = _) |> 
  mutate(id = row_number()) |> 
  extract(x, into = c("x","m","a","s"), "{x=(\\d+),m=(\\d+),a=(\\d+),s=(\\d+)}", convert = TRUE)

```

--- Part 1 ---

```{r}
apply_workflow <- function(x, w = "in"){
  rules <- strsplit(workflows[w], ",") |> unlist()
  i <- 0
  while(i <= length(rules)){
    i <- i + 1
    r <- rules[[i]]
    if (identical(r,"A")) return("A")
    if (identical(r,"R")) return("R")
    if (grepl(":",r)) {
      pattern <- gsub(x = r, pattern = "(.+)\\:(.+)", replacement = "\\1")
      outcome <- gsub(x = r, pattern = "(.+)\\:(.+)", replacement = "\\2")
      if(with(x, eval(parse(text = pattern)))) {
        if (identical(outcome,"A")) return("A")
        if (identical(outcome,"R")) return("R")
        return(apply_workflow(x, w = outcome))
      }
      next
    }
    if (!grepl(":", r)) return(apply_workflow(x, r))
  }
  stop("wtf")
}

ratings |> 
  mutate(
    ok = sapply(seq_len(nrow(ratings)), \(x) apply_workflow(ratings[x,]))
  ) |> 
  filter(ok == "A") |> 
  summarise(sum(x,m,a,s))

```

--- Part 2 ---
_in progress_

this looks like that recursive range splitting problem from day five. 

i'm not a fan of this theme that seems to be appearing (as coined by @jonocarroll)
of:

> Day N: "You should learn XYZ to solve this problem"
>
> Day N+10: "I wasn't asking" :muscle:

```{r}
parse_workflow <-  \(w = "in", x = list(x = 1:4000, m = 1:4000, a = 1:4000, s = 1:4000)){
  ok <- vector("list")
  rules <- strsplit(workflows[w], ",") |> unlist()
  i <- 0
  while(i <= length(rules)){
    i <- i + 1
    r <- rules[[i]]
    if (identical(r, "A")) {ok <- c(ok, list(x)); return(ok)}
    if (identical(r, "R")) return(ok)
    if (grepl(":",r)){
      var <- substr(r,1,1)
      pattern <- gsub(x = r, pattern = "(.+)\\:(.+)", replacement = "\\1")
      x_matches <- x
      x_matches[[var]] <- x[[var]][eval(parse(text = pattern),envir = x)]
      x[[var]] <- x[[var]][!eval(parse(text = pattern), envir = x)]
      outcome <- gsub(x = r, pattern = "(.+)\\:(.+)", replacement = "\\2")
      if (identical(outcome, "A")) {ok <- c(ok, list(x_matches)); next}
      if (identical(outcome, "R")) next
      ok <- c(ok, parse_workflow(outcome, x = x_matches))
    }
    
    if (!grepl(":", r)) {ok <- c(ok, parse_workflow(r, x)); return(ok);}
  }
  
  return(ok)
}

parse_workflow() |> sapply(\(x) lengths(x) |> prod()) |> sum()

```

