---
title: 'Advent Of Code: 2018-03'
author: "Tan Ho"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 3, year = 2018)
```

```{r}
input <- tibble(x = readLines(here::here("2018/day-03-input.txt")) |> 
                  stringr::str_squish()) |> 
  tidyr::extract(x, 
          into = c("elf_id", "x_coord", "y_coord", "x_size", "y_size"),
          ".([0-9]+)\\s*.\\s+([0-9]+).([0-9]+)\\s*.\\s*([0-9]+).([0-9]+)",
          convert = TRUE
          )

example <- tibble(
  elf_id = 1:3,
  x_coord = c(1,3,5),
  y_coord = c(3,1,5),
  x_size = c(4,4,2),
  y_size = c(4,4,2)
)

```

--- Part 1 ---

```{r}

p1 <- input |> 
  transmute(
    elf_id,
    coords = pmap(list(x_coord,x_size,y_coord,y_size), ~crossing(x = ..1:(..1+..2-1),
                                                                y = ..3:(..3+..4-1)))
  ) |> 
  unnest(coords) |> 
  count(x,y)

p1 |> 
  filter(n>1) |> 
  nrow()

```

--- Part 2 ---

```{r}
p2 <- input |> 
  transmute(
    elf_id,
    coords = pmap(list(x_coord,x_size,y_coord,y_size), ~crossing(x = ..1:(..1+..2-1),
                                                                y = ..3:(..3+..4-1)))
  ) |> 
  unnest(coords) |> 
  add_count(x,y)

p2 |> 
  group_by(elf_id) |> 
  summarise(
    claim = mean(n, na.rm = TRUE)
  ) |> 
  filter(claim == 1) |> 
  pull(elf_id)

```

