---
title: 'Advent Of Code: 2019-02'
author: "Tan Ho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 2, year = 2019)
```

```{r}
input <- readLines(here::here("2019/day-02-input.txt")) |> 
  strsplit(",") |> 
  unlist() |> 
  as.numeric()

example <- c("1,1,1,4,99,5,6,0,99") |> 
  strsplit(",") |> 
  unlist() |> 
  as.numeric()
```

--- Part 1 ---

```{r}

add <- function(in1,in2,out,vec){
  vec[out+1] <- vec[in1+1] + vec[in2+1]
  vec
}

mult <- function(in1,in2,out,vec){
  vec[out+1] <- vec[in1+1] * vec[in2+1]
  vec
}

i <- 1

p1 <- input

p1[2] <- 12
p1[3] <- 2

while (p1[i]!=99){
  switch(p1[i],
         "1" = p1 <- add(p1[i+1], p1[i+2], p1[i+3], p1),
         "2" = p1 <- mult(p1[i+1], p1[i+2], p1[i+3], p1)
  )
  i <- i+4
}

p1[1]

```

--- Part 2 ---

```{r}

attempts <- crossing(noun = 1:100, verb = 1:100)

intcode_program <- function(noun,verb, input){
  p <- input
  p[2] <- noun
  p[3] <- verb
  i <- 1
  while (p[i]!=99){
    switch(p[i],
           "1" = p <- add(p[i+1], p[i+2], p[i+3], p),
           "2" = p <- mult(p[i+1], p[i+2], p[i+3], p)
    )
    i <- i+4
  }
  
  return(p[1])
}

attempts |> 
  mutate(
    output = map2_dbl(noun,verb,intcode_program,input)
  ) |> 
  filter(output == 19690720)

```

--- Intcode Program to Date ---

```{r}
add <- function(in1,in2,out,vec){
  vec[out+1] <- vec[in1+1] + vec[in2+1]
  vec
}

mult <- function(in1,in2,out,vec){
  vec[out+1] <- vec[in1+1] * vec[in2+1]
  vec
}

intcode_program <- function(noun,verb, input){
  p <- input
  p[2] <- noun
  p[3] <- verb
  i <- 1
  while (p[i]!=99){
    switch(p[i],
           "1" = p <- add(p[i+1], p[i+2], p[i+3], p),
           "2" = p <- mult(p[i+1], p[i+2], p[i+3], p)
    )
    i <- i+4
  }
  
  return(p[1])
}

```

