---
title: 'Advent Of Code: 2019-05'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 5, year = 2019)
```

```{r}
input <- readLines(here::here("2019/day-05-input.txt"))
```

--- Part 1 ---

Recap: intcode program to date.

```{r}
op_add <- function(in1,in2,out,vec){
  vec[out+1] <- vec[in1+1] + vec[in2+1]
  vec
}

op_mult <- function(in1,in2,out,vec){
  vec[out+1] <- vec[in1+1] * vec[in2+1]
  vec
}

op_save <- function(input,pos,vec){
  vec[pos] <- input
  vec
}

op_return <- function(input)

intcode_program <- function(noun,verb, input){
  p <- input
  p[2] <- noun
  p[3] <- verb
  i <- 1
  while (p[i]!=99){
    switch(p[i],
           "1" = p <- op_add(p[i+1], p[i+2], p[i+3], p),
           "2" = p <- op_mult(p[i+1], p[i+2], p[i+3], p)
    )
    i <- i+4
  }
  
  return(p[1])
}

```

--- Part 2 ---

```{r}

```

