---
title: 'Advent Of Code: 2015-03'
author: "Tan Ho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 3, year = 2015)
```

```{r}
input <- readLines(here::here("2015/day-03-input.txt")) |>
  strsplit("") |>
  unlist()

```

--- Part 1 ---

```{r}
visit <- function(position,move){
  switch(move,
         ">" = position[1] <- position[1] + 1,
         "<" = position[1] <- position[1] - 1,
         "^" = position[2] <- position[2] + 1,
         "v" = position[2] <- position[2] - 1,
  )
  return(position)
}

purrr::accumulate(input,visit, .init = c(0,0)) |> unique() |> length()

```

--- Part 2 ---

divvy up half to santa and half to robosanta

```{r}

santa <- input[rep_len(c(TRUE,FALSE),length(input))]
robosanta <- input[rep_len(c(FALSE,TRUE),length(input))]

c(purrr::accumulate(santa,visit, .init = c(0,0)),
  purrr::accumulate(robosanta,visit, .init = c(0,0))) |> 
  unique() |> 
  length()

```

