---
title: 'Advent Of Code: 2016-04'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 4, year = 2016)
```

```{r}
input <- tibble(x = readLines(here::here("2016/day-04-input.txt"))) |> 
  extract(x, into = c("name","sector_id","checksum"),
          regex = "([a-z,\\-]+)\\-([0-9]+)\\[([a-z]+)\\]")
```

--- Part 1 ---

```{r}
p1 <- input |> 
  mutate(name = str_remove_all(name,"\\-") |> strsplit(""),
         check = map_chr(name,
                      ~tibble(x = .x) |> 
                        count(x) |> 
                        arrange(-n,x) |> 
                        pull(x) |> 
                        head(5) |> 
                        paste(collapse = "")
                      )) |>
  filter(check == checksum)

p1 |> 
  pull(sector_id) |> 
  as.numeric() |> 
  sum()

```

--- Part 2 ---

```{r}

l2n <- tibble(letter = letters, num = 1:26) |> deframe()

p2 <- p1 |> 
  mutate(
    shift = as.numeric(sector_id) |> magrittr::mod(26),
    decoded = map2(
      name,shift,
      ~paste(letters[(l2n[.x]+.y)%%26],collapse = "")
                  )
  )

p2 |> 
  filter(str_detect(decoded,"northpoleobjectstorage")) |> 
  pull(sector_id)

```

