---
title: 'Advent Of Code: 2016-03'
author: "Tan Ho"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 3, year = 2016)
```

```{r}
input <- readLines(here::here("2016/day-03-input.txt"))
```

--- Part 1 ---

```{r}
p1 <- tibble(x = input) |> 
  extract(x, into = c("x","y","z"), regex = "([0-9]+) +([0-9]+) +([0-9]+)") |> 
  mutate_all(as.numeric) |> 
  mutate(
    xy = x+y > z,
    xz = x+z > y,
    yz = y+z > x,
    test = xy & xz & yz
  ) |> 
  filter(test)

nrow(p1)
```

--- Part 2 ---

```{r}
p2 <- tibble(x = input) |> 
  extract(x, into = c("x","y","z"), regex = "([0-9]+) +([0-9]+) +([0-9]+)") |> 
  mutate_all(as.numeric) |> 
  mutate(
    group = (row_number()+2) %/% 2.99999
  ) |> 
  pivot_longer(c(x,y,z),names_to = "id") |> 
  group_by(group,id) |> 
  mutate(
    name = c("x","y","z")
  ) |> 
  pivot_wider(names_from = name, values_from = value) |> 
  mutate(
    xy = x+y > z,
    xz = x+z > y,
    yz = y+z > x,
    test = xy & xz & yz
  ) |> 
  filter(test)
nrow(p2)
```

