---
title: 'Advent Of Code: 2022-15'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

<https://adventofcode.com/2022/day/15>

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 15, year = 2022)
```

```{r}
input_raw <- readLines(here::here("2022/day-15-input.txt"))
input <- aoc.elf::aoc_read(day = 15, year = 2022) |> 
  mutate(id = row_number()) |> 
  separate(1, into = c("sensor","beacon"), sep = ": ",remove = F) |> 
  separate(sensor, into = c("sx","sy"), sep = ",") |> 
  separate(beacon, into = c("bx","by"), sep = ",") |> 
  mutate(across(c(sx,sy,bx,by),parse_number),
         d = abs(sx-bx) + abs(sy-by))

example <- c("Sensor at x=2, y=18: closest beacon is at x=-2, y=15", "Sensor at x=9, y=16: closest beacon is at x=10, y=16", "Sensor at x=13, y=2: closest beacon is at x=15, y=3", "Sensor at x=12, y=14: closest beacon is at x=10, y=16", "Sensor at x=10, y=20: closest beacon is at x=10, y=16", "Sensor at x=14, y=17: closest beacon is at x=10, y=16", "Sensor at x=8, y=7: closest beacon is at x=2, y=10", "Sensor at x=2, y=0: closest beacon is at x=2, y=10", "Sensor at x=0, y=11: closest beacon is at x=2, y=10", "Sensor at x=20, y=14: closest beacon is at x=25, y=17", "Sensor at x=17, y=20: closest beacon is at x=21, y=22", "Sensor at x=16, y=7: closest beacon is at x=15, y=3", "Sensor at x=14, y=3: closest beacon is at x=15, y=3", "Sensor at x=20, y=1: closest beacon is at x=15, y=3") |> 
  tibble(x = _) |> 
  separate(1, into = c("sensor","beacon"), sep = ": ",remove = F) |> 
  separate(sensor, into = c("sx","sy"), sep = ",") |> 
  separate(beacon, into = c("bx","by"), sep = ",") |> 
  mutate(across(c(sx,sy,bx,by),parse_number),
         d = abs(sx-bx) + abs(sy-by))


```

--- Part 1 ---

```{r}

manhattan_x_on_v <- function(sx,sy,d, v = 2e6){
  r <- c(sy + d, sy - d)
  # if no point falls on the 2M line then exit
  if(!dplyr::between(v, min(r),max(r))) return(NULL)
  
  dy <- abs(sy - v)
  
  dx <- seq.int(1, d - dy)
  return(c(sx + dx, sx - dx, sx))
}

# e1 <- pmap(list(example$sx, example$sy, example$d), manhattan_x_on_v, v = 10) |> 
#   unlist() |> 
#   unique()
# 
# length(e1) - distinct(example,bx,by) |> filter(by == 10) |> nrow()

p1 <- pmap(list(input$sx,input$sy,input$d), manhattan_x_on_v) |> 
  unlist() |> 
  unique()

length(p1) - distinct(input,bx,by) |> filter(by == 2e6) |> nrow()

```

--- Part 2 ---

Brute force ish, but narrowed sample size by looking on points just on the edge of manhattan-distance away and then checking to make sure it's not near any other sensor.
```{r eval = FALSE}
library(data.table)

nonadjacent_points <- \(sx,sy,d){
  dd <- d + 1
  list(
    x = c(sx + seq.int(0,dd), sx + seq.int(dd,0), sx + seq.int(-dd,0), sx + seq.int(0,-dd)),
    y = c(sy + seq.int(dd,0), sy + seq.int(0,dd), sy + seq.int(0,-dd), sy + seq.int(-dd,0))
  )
}
sensors <- input |> select(x = sx, y = sy, d)

candidates <- list(input$sx,input$sy,input$d) |> 
  pmap(nonadjacent_points) |> 
  rbindlist() |> 
  unique()

candidates <- candidates[x >= 0 & x <= 4e6 & y >= 0 & y <= 4e6]

check_range <- \(x,y){
  !any((abs(x - sensors$x) + abs(y - sensors$y)) <= sensors$d)
}

i <- 1

repeat{
  if(i %% 100000 == 0) cat(i, sep = "\n")
  beacon <- check_range(candidates$x[i],candidates$y[i])
  if(beacon) break
  i <- i + 1
}
candidates$x[i] * 4e6 + candidates$y[i]
```
```{r echo = FALSE}
12480406634249
```

