---
title: 'Advent Of Code: 2022-03'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 3, year = 2022)
```

```{r}
input_raw <- readLines(here::here("2022/day-03-input.txt"))
input <- aoc.elf::aoc_read(day = "03", year = "2022")
```

--- Part 1 ---

```{r}
dictionary <- c(letters,LETTERS)
p1 <- input |> 
  mutate(
    x = strsplit(x,""),
    len = lengths(x),
    c1 = purrr::map2(x,len, ~.x[seq_len(.y/2)]),
    c2 = purrr::map2(x,len,~.x[(.y/2+1):.y]),
    common = purrr::map2_dbl(c1,c2,~intersect(.x,.y) |> match(dictionary) |> sum())
  ) 

sum(p1$common)
```

--- Part 2 ---

```{r}
input |> 
  mutate(
    x = strsplit(x,""),
    group = row_number()%/%3.000001
  ) |> 
  group_by(group) |> 
  mutate(id = row_number()) |> 
  pivot_wider(names_from = id, names_prefix = "a", values_from = x) |> 
  mutate(
    common = purrr::pmap_dbl(list(a1,a2,a3), 
                             ~intersect(..1,..2) |> 
                               intersect(..3) |> 
                               match(dictionary))
  ) |> 
  pull(common) |> 
  sum()
```

