---
title: 'Advent Of Code: 2022-04'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 4, year = 2022)
```

```{r}
input <- aoc.elf::aoc_read(day = 4, year = 2022) |> 
  separate(1, 
           sep = ",|\\-", 
           into = c("x1","x2", "y1", "y2"),
           convert = TRUE)
```

--- Part 1 ---

```{r}
p1 <- input |> 
  mutate(
    x = purrr::map2(x1,x2,~.x:.y),
    y = purrr::map2(y1,y2,~.x:.y),
    xd = purrr::map2(x,y,setdiff),
    yd = purrr::map2(y,x,setdiff)
    ) |> 
  filter(lengths(xd) == 0 | lengths(yd) == 0)
nrow(p1)
```

--- Part 2 ---

```{r}
p2 <- input |> 
  mutate(
    x = purrr::map2(x1,x2,~.x:.y),
    y = purrr::map2(y1,y2,~.x:.y),
    intersect = purrr::map2(x,y,intersect)
    ) |> 
  filter(lengths(intersect) > 0)
nrow(p2)
```

