---
title: 'Advent Of Code: 2022-05'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 5, year = 2022)
```

```{r}
input_raw <- readLines(here::here("2022/day-05-input.txt"))
stacks <- head(input_raw,8) |> 
  paste(collapse = "\n") |> 
  read_fwf() |> 
  set_names(paste0("s",1:9))

stack_list <- stacks |> 
  as.list() |> 
  map(na.omit)

moves <- tail(input_raw,-10) |> 
  tibble() |> 
  extract(1, 
          into = c("count","from","to"), 
          regex = "move (\\d+) from (\\d+) to (\\d+)", 
          convert = TRUE)
```

--- Part 1 ---

```{r}

do_move <- function(sl, count, from, to){
  crates <- head(sl[[from]], count)
  sl[[from]] <- tail(sl[[from]], -count)
  sl[[to]] <- c(rev(crates), sl[[to]])
  sl
}
sl <- stack_list
for(i in seq_len(nrow(moves))){
  sl <- do_move(sl, moves$count[i], moves$from[i], moves$to[i])
}
map_chr(sl,head,1) |> paste(collapse = "") |> str_replace_all("\\[|\\]","")

```

--- Part 2 ---

```{r}

do_move <- function(sl, count, from, to){
  crates <- head(sl[[from]], count)
  sl[[from]] <- tail(sl[[from]], -count)
  sl[[to]] <- c(crates, sl[[to]])
  sl
}
sl <- stack_list
for(i in seq_len(nrow(moves))){
  sl <- do_move(sl, moves$count[i], moves$from[i], moves$to[i])
}
map_chr(sl,head,1) |> paste(collapse = "") |> str_replace_all("\\[|\\]","")
```

