---
title: 'Advent Of Code: 2022-13'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

<https://adventofcode.com/2022/day/13>

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 13, year = 2022)
```

```{r}
input <- aoc.elf::aoc_read(day = 13, year = 2022) |> 
  mutate(id = cumsum(is.na(x)) + 1) |> 
  filter(!is.na(x)) |> 
  group_by(id) |> 
  mutate(p = row_number()) |> 
  ungroup() |> 
  pivot_wider(names_from = p, values_from = x, names_prefix = "p")

example <- c("[1,1,3,1,1]", "[1,1,5,1,1]", NA, "[[1],[2,3,4]]", "[[1],4]", NA, "[9]", "[[8,7,6]]", NA, "[[4,4],4,4]", "[[4,4],4,4,4]", NA, "[7,7,7,7]", "[7,7,7]", NA, "[]", "[3]", NA, "[[[]]]", "[[]]", NA, "[1,[2,[3,[4,[5,6,7]]]],8,9]", "[1,[2,[3,[4,[5,6,0]]]],8,9]") |> 
  tibble(x = _) |> 
  mutate(id = cumsum(is.na(x)) + 1) |> 
  filter(!is.na(x)) |> 
  group_by(id) |> 
  mutate(p = row_number()) |> 
  ungroup() |> 
  pivot_wider(names_from = p, values_from = x, names_prefix = "p")

```

--- Part 1 ---

if both values are ints, 

if LHS < RHS good
if LHS > RHS bad
if LHS = RHS next

if both values are lists, do int-check. 


```{r}
parse_brackets <- \(x) str_replace_all(x, "\\[","list(") |> str_replace_all("\\]",")") |> parse(text = _) |> eval()

compare_packets <- \(left,right){
  
  if(is.null(left) && length(right) > 0) return(TRUE)
  if(is.null(right) && length(left) > 0) return (FALSE)
  if(is.null(left) && is.null(right)) browser()
  
  if(is.numeric(left) && is.numeric(right)) {
    if(left < right) return(TRUE)
    if(right < left) return(FALSE)
    if(left == right) return(NULL)
  }
  
  if(is.list(left) && is.numeric(right)) {
    right <- list(right)
    return(compare_packets(left,right))
  }
  
  if(is.numeric(left) && is.list(right)) {
    left <- list(left)
    return(compare_packets(left,right))
  }
  
  if(is.list(left) && is.list(right)) {
    i <- 0
    out <- NULL
    while(is.null(out)) {
      i <- i + 1
      
      if(length(left) < i && length(right) < i) return(NULL)
      if(length(left) < i) return(TRUE)
      if(length(right) < i ) return(FALSE)
      
      out <- compare_packets(left[[i]], right[[i]])
    }
  }
  return(out)
}

input |> 
  mutate(flag = purrr::map2_lgl(p1, p2, ~compare_packets(parse_brackets(.x), parse_brackets(.y)))) |> 
  mutate(val = flag * id) |> 
  summarise(sum(val)) |> 
  pull()

```

--- Part 2 ---

```{r}
divider_packets <- c("[[2]]","[[6]]")
all_packets <- readLines(here::here("2022/day-13-input.txt"))
all_packets <- c(unique(all_packets[!all_packets == ""]),divider_packets)

sorted_packets <- all_packets[1]
packets_to_sort <- setdiff(all_packets, sorted_packets)


for(packet in packets_to_sort){
  i <- 0
  repeat{
    i <- i + 1
    if(i > length(sorted_packets)) {
      sorted_packets <- c(sorted_packets, packet)
      packets_to_sort <- tail(packets_to_sort, -1)
      break
    }
    
    packet_check <- compare_packets(parse_brackets(sorted_packets[i]),parse_brackets(packet))
    
    if(!packet_check) {
      sorted_packets <- append(sorted_packets,packet,after = i-1)
      packets_to_sort <- tail(packets_to_sort,-1)
      break
    }
  }
}

which(sorted_packets %in% divider_packets) |> prod()

```

