---
title: 'Advent Of Code: 2022-17'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

<https://adventofcode.com/2022/day/17>

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 17, year = 2022)
```

```{r}
input <- readLines(here::here("2022/day-17-input.txt")) |> 
  strsplit("") |> 
  unlist()

rocks <- list(
  r1 = matrix(1, ncol = 4),
  r2 = matrix(c(0,1,0,1,1,1,0,1,0), nrow = 3, ncol = 3, byrow = TRUE),
  r3 = matrix(c(0,0,1,0,0,1,1,1,1), nrow = 3, ncol = 3, byrow = TRUE),
  r4 = matrix(1, nrow = 4),
  r5 = matrix(1, ncol = 2, nrow = 2)
)

example <- ">>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>" |> strsplit("") |> unlist()
```

--- Part 1 ---

```{r}
mat <- matrix(1, ncol = 7)
jets <- input

rock_list <- rocks |> lapply(\(.x) {
  x <- which(.x == 1, arr.ind = TRUE)
  x[,2] <- x[,2] + 2
  x
  })

rock_num <- 1
rock_type <- 1
jet_num <- 1
while(rock_num <= 2022){
  pos <- rock_list[[rock_type]]
  mat <- rbind(matrix(0, nrow = 3 + max(pos[,1]), ncol = 7), mat)  
  
  repeat {
    j <- jets[jet_num]
    if(j == ">" && all((pos[,2]) < 7) && all(mat[cbind(pos[,1],(pos[,2] + 1))]==0)) pos[,2] <- pos[,2] + 1
    if(j == "<" && all((pos[,2]) > 1) && all(mat[cbind(pos[,1],(pos[,2] - 1))]==0)) pos[,2] <- pos[,2] - 1
    jet_num <- jet_num %% length(jets) + 1
    # temp <- mat
    # temp[pos] <- 1
    # print(temp)
    if(any(mat[cbind((pos[,1] + 1), pos[,2])] == 1)) break
    pos[,1] <- pos[,1] + 1
  }
  
  mat[pos] <- 1
  mat <- mat[apply(mat,1,sum)!=0,] |> unname()
  rock_num <- rock_num + 1
  rock_type <- (rock_type %% 5) + 1
}

nrow(mat)-1

```

--- Part 2 ---

Okay, so clearly the solve is not related to running the matrix growth 1e12 times. 

```{r}
mat <- matrix(1, ncol = 7)
jets <- input

rock_list <- rocks |> lapply(\(.x) {
  x <- which(.x == 1, arr.ind = TRUE)
  x[,2] <- x[,2] + 2
  x
  })

rock_num <- 1
rock_type <- 1
jet_num <- 1
heights <- integer()
while(rock_num <= 4000){
  pos <- rock_list[[rock_type]]
  mat <- rbind(matrix(0, nrow = 3 + max(pos[,1]), ncol = 7), mat)  
  
  repeat {
    j <- jets[jet_num]
    if(j == ">" && all((pos[,2]) < 7) && all(mat[cbind(pos[,1],(pos[,2] + 1))]==0)) pos[,2] <- pos[,2] + 1
    if(j == "<" && all((pos[,2]) > 1) && all(mat[cbind(pos[,1],(pos[,2] - 1))]==0)) pos[,2] <- pos[,2] - 1
    jet_num <- jet_num %% length(jets) + 1
    if(any(mat[cbind((pos[,1] + 1), pos[,2])] == 1)) break
    pos[,1] <- pos[,1] + 1
  }
  
  mat[pos] <- 1
  mat <- mat[apply(mat,1,sum)!=0,] |> unname()
  heights[rock_num] <- nrow(mat)
  rock_num <- rock_num + 1
  rock_type <- (rock_type %% 5) + 1
}
```

```{r}
height_diff <-  (heights - 1) - dplyr::lag(heights - 1,default = 0)
hd <- paste(height_diff,collapse = "")
seq_diff <- stringr::str_locate_all(hd,substr(hd,500,550))[[1]][,1] |> diff() |> unique()

cycles <- (1000000000000 - 500) %/% 1700
cycle_height <- sum(height_diff[seq_len(seq_diff) + 500])

modulo <- (1000000000000 - 500) %% 1700
modulo_height <- sum(height_diff[seq_len(modulo) + 500])

total_height <- cycle_height * cycles + modulo_height + sum(height_diff[1:500])
options(scipen = 99)
total_height
```

