---
title: 'Advent Of Code: 2022-08'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 8, year = 2022)
```

```{r}
input <- readLines(here::here("2022/day-08-input.txt")) |> 
  strsplit("") |> 
  reduce(rbind)

mode(input) <- "integer"

```

--- Part 1 ---

```{r}

find_visible <- function(row,col){
  value <- input[row,col]
  
  north <- sum(input[seq_len(row),col] >= value)
  south <- sum(input[row:nrow(input),col] >= value)
  east <- sum(input[row,col:ncol(input)] >= value)
  west <- sum(input[row,seq_len(col)] >= value)
  
  
  
  if(any(c(north, south, east, west)==1)) return(TRUE)
  return(FALSE)
}

p1 <- crossing(r = seq_len(nrow(input)), c = seq_len(ncol(input))) |> 
  mutate(visible = map2_dbl(r,c,find_visible))
sum(p1$visible)

```

--- Part 2 ---

```{r}

count_internal <- function(row,col){
  
  value <- input[row,col]
  
  north <- rle(tail(rev(input[seq_len(row),col]),-1) >= value)
  west <- rle(tail(rev(input[row,seq_len(col)]), -1) >= value)
  south <- rle(tail(input[row:nrow(input),col], -1) >= value)
  east <- rle(tail(input[row,col:ncol(input)], -1)>= value)
  
  list(north,west,south,east) |> 
    purrr::discard(~length(.x) == 0) |> 
    sapply(\(x){
      if(x$values[1] == TRUE) return(1)
      if(x$values[1] == FALSE && length(x$values) == 1) return(x$lengths[[1]])
      if(x$values[1] == FALSE && length(x$values) > 1) return(x$lengths[[1]] + 1)
      return(0)
    }) |> 
    prod()
  
}

p2 <- crossing(r = seq_len(nrow(input)), c = seq_len(ncol(input))) |> 
  mutate(visible = map2_dbl(r,c,count_internal))

sum(p2$visible)


```

