---
title: 'Advent Of Code: 2021-14'
author: Tan Ho
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 14, year = 2021)
```

```{r}
input <- readLines(here::here("2021/day-14-input.txt"))
# 
# input <- c(
#   "NNCB",
#   "",
#   "CH -> B",
#   "HH -> N",
#   "CB -> H",
#   "NH -> C",
#   "HB -> C",
#   "HC -> B",
#   "HN -> C",
#   "NN -> C",
#   "BH -> H",
#   "NC -> B",
#   "NB -> B",
#   "BN -> B",
#   "BB -> N",
#   "BC -> B",
#   "CC -> N",
#   "CN -> C"
# )

polymer <- input[1]

subs <- tibble(x = input[-c(1:2)]) |> 
  separate(x, into = c("match","insert")," -> ")

```

--- Part 1 ---

```{r eval = FALSE}

check_substitution <- \(search,polymer){
  
  p1 <- polymer |> strsplit("") |> unlist()
  p <- paste0(p1,lead(p1,default = "1"))
  
  return(which(p == search))
}

insert_subs <- \(polymer, insert_char, start_loc){
  end_loc <- start_loc + 1
  
  paste0(substr(polymer,1,start_loc),insert_char,substr(polymer,end_loc,str_length(polymer)))
}

polymer_substitution <- function(polymer,step){
  
  cat(step, sep = "\n")
  
  x <- subs |> 
    mutate(
      start = map(match,check_substitution,polymer)
    ) |> 
    unnest(start) |> 
    arrange(start) |> 
    mutate(
      start = start + row_number() -1
    )
  
  reduce2(x$insert,x$start,insert_subs,.init = polymer)
}

x <- reduce(1:10,polymer_substitution,.init = polymer)

y <- tibble(char = x |> strsplit("") |> unlist()) |> 
  count(char) |> 
  pull(n) |> 
  range() |> 
  diff()
```
```{r echo = FALSE}
3906
```

--- Part 2 ---

Mind blanked today on the not-naive solution to growing a vector - took me until the 90 minute mark to start looking for better algorithms and I ended up needing reddit's assistance to think of storing a count of each pair. This was not one of my more brilliant nights.

```{r}

dictionary_count <- subs |> 
  mutate(
    n = str_count(polymer,match)
  )

join_dictionary <- subs |> 
  mutate(
    left = paste0(str_sub(match,1,1),insert),
    right = paste0(insert,str_sub(match,2,2))
  ) |> 
  pivot_longer(c("left","right")) |> 
  select(match,value)

do_polymer <- function(counts, step){
  
  x <- counts |> 
    full_join(join_dictionary, by = "match") |> 
    group_by(match = value) |> 
    summarise(
      n = sum(n, na.rm = TRUE)
    )
  
  return(x)
}

pairs <- reduce(1:10,do_polymer,.init = dictionary_count)

pairs |> 
  mutate(letters = strsplit(match,"")) |> 
  unnest_longer(letters) |> 
  group_by(letters) |> 
  summarise(n = sum(n, na.rm = TRUE)) |> 
  ungroup() |> 
  mutate(
    n = case_when(
      letters == str_sub(polymer,1,1) ~ n+1,
      letters == str_sub(polymer,-1,-1) ~ n+1,
      TRUE ~ as.numeric(n)),
    n = n/2)  |> 
  pull(n) |> 
  range() |> 
  diff()

```

