---
title: 'Advent Of Code: 2021-05'
author: "Tan Ho"
date: "2021-12-04"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  library(tantastic)
  
  ragg_png = function(..., res = 150) {
    ragg::agg_png(..., res = res, units = "in")
  }
  knitr::opts_chunk$set(dev = "ragg_png")
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
aoc.elf::aoc_get(5)
```

```{r}
i <- readLines(here::here("2021/day-05-input.txt"))
```

```{r}
input <- tibble(x = i) |> 
  extract(x, c("x1","y1","x2","y2"),regex = "([0-9]+),([0-9]+) -> ([0-9]+),([0-9]+)",convert = TRUE) |> 
  mutate(
    line_id = row_number()
  )
```

--- Part 1 ---

Using map2, create a nested list for each point and then unnest and group-by+count the duplicates

```{r}
p1 <- input |> 
  filter(x1 == x2 | y1 == y2) |> 
  mutate(
    x = map2(x1,x2,~.x:.y),
    y = map2(y1,y2,~.x:.y)
  ) |> 
  select(line_id, x, y) |> 
  unnest(c(x,y)) |> 
  group_by(x,y) |> 
  summarise(
    dupl = n()
  ) |> 
  filter(
    dupl > 1
  )

nrow(p1)
```

--- Part 2 ---

Very lucky that this solution generalizes by just removing the filter!

```{r}
p2 <- input |> 
  mutate(
    x = map2(x1,x2,~.x:.y),
    y = map2(y1,y2,~.x:.y)
  ) |> 
  select(line_id, x, y) |> 
  unnest(c(x,y)) |> 
  group_by(x,y) |> 
  summarise(
    dupl = n()
  ) |> 
  filter(
    dupl > 1
  )

nrow(p2)
```

I am unbelievably excited to have placed in the top 500!

And per Joe's request, a plotses!

```{r warning=FALSE, message = FALSE}
input |> 
  mutate(
    x = map2(x1,x2,~.x:.y),
    y = map2(y1,y2,~.x:.y)
  ) |> 
  select(line_id, x, y) |> 
  unnest(c(x,y)) |> 
  ggplot(aes(x = x, y = y, color = line_id, fill = line_id, group = line_id)) + 
  geom_line(alpha = 0.75) + 
  labs(
    title = "Advent Of Code Day 5: Hydrothermal Venture",
    caption = "@_TanHo"
  ) + 
  tantastic::theme_tantastic() + 
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )
```

